### ISSUE TITLE
Mistake in parsing map data

### ISSUE THREAD

**Issue by toyamaguchi** [nacika-ins/json_flex#6]
Hello, nacika.

I'm user of json_flex. I like this library very much!
But, today I found mistake in parsing map data.

Firstly, I show bad example.

- input data: {"a": { "b": { "c": 1 }, "d": "e" }}
- to_json(): {"a":{"b":{"d":"e","c":1}}}

The map {"d": "e"} is included in the map "b".

But, if the number object 1 is changed to the string "OK", it can be parsed successfully.

- input data: {"a": { "b": { "c": "OK" }, "d": "e" }}
- to_json(): {"a":{"b":{"c":"OK"},"d":"e"}}

Maybe, there is a mistake after parsing number object, I guess...

If this issue is fixed, I can continue to use this library.
So, please investigate this issue.
Thanks in advance.

**Comment by toyamaguchi** [comment]
I could find this issue affects not only number in map but also other types of object.
Maybe, true, false, float data also cannot be parsed.

So, I created special test data for this issue.

- input_data: {"str":{"key":"ABC"},"int":{"key":0},"float":{"key":0.1},"map":{"key":{"k":"v"}},"vector":{"key":[0,1,2]},"null":{"key":null},"true":{"key":true},"false":{"key":false},"last":"last"}
- to_json(): {"int":{"float":{"map":{"key":{"k":"v"}},"vector":{"key":[0,1,2]},"null":{"key":null,"true":{"key":true,"false":{"last":"last","key":false}}},"key":0.1},"key":0},"str":{"key":"ABC"}}

Currently, json_flex cannot parse this data correctly.
So, it needs to be fixed to parse this data correctly.

**Comment by toyamaguchi** [comment]
Dear nacika,

I try to fix code and send pull request.
If you review it, I'm glad.
Thanks in advance.

**Comment by nacika-ins** [comment]
thanks
